/**
 * UK tech employers whose public ATS job boards feed the job cache.
 *
 * Every slug was fetched live and returned HTTP 200 with valid JSON, with at least
 * one UK-located posting. The run is recorded in docs/employer-feed-verification.md.
 * Add an employer only after repeating that check. A wrong slug is harmless (the
 * fetch fails and the cron skips it) but a slug that belongs to a different company
 * would list the wrong firm's roles under this name.
 */
export type Ats = "greenhouse" | "lever" | "ashby";

export interface Employer {
  name: string;
  ats: Ats;
  slug: string;
}

export const EMPLOYERS: Employer[] = [
  { name: "Adyen", ats: "greenhouse", slug: "adyen" },
  { name: "Affirm", ats: "greenhouse", slug: "affirm" },
  { name: "Airbnb", ats: "greenhouse", slug: "airbnb" },
  { name: "Aircall", ats: "lever", slug: "aircall" },
  { name: "Airtable", ats: "greenhouse", slug: "airtable" },
  { name: "Airwallex", ats: "ashby", slug: "airwallex" },
  { name: "Akuna Capital", ats: "greenhouse", slug: "akunacapital" },
  { name: "Algolia", ats: "greenhouse", slug: "algolia" },
  { name: "Amplitude", ats: "ashby", slug: "amplitude" },
  { name: "Anthropic", ats: "greenhouse", slug: "anthropic" },
  { name: "Asana", ats: "greenhouse", slug: "asana" },
  { name: "Auto Trader", ats: "greenhouse", slug: "autotrader" },
  { name: "Beamery", ats: "ashby", slug: "beamery" },
  { name: "Binance", ats: "lever", slug: "binance" },
  { name: "Block", ats: "greenhouse", slug: "block" },
  { name: "Blockchain.com", ats: "greenhouse", slug: "blockchain" },
  { name: "Braze", ats: "greenhouse", slug: "braze" },
  { name: "Bugcrowd", ats: "greenhouse", slug: "bugcrowd" },
  { name: "Bybit", ats: "greenhouse", slug: "bybit" },
  { name: "Capital on Tap", ats: "greenhouse", slug: "capitalontap" },
  { name: "Checkatrade", ats: "ashby", slug: "checkatrade" },
  { name: "ClearBank", ats: "ashby", slug: "clearbank" },
  { name: "ClickHouse", ats: "ashby", slug: "clickhouse" },
  { name: "Cockroach Labs", ats: "greenhouse", slug: "cockroachlabs" },
  { name: "Codat", ats: "ashby", slug: "codat" },
  { name: "Cognism", ats: "greenhouse", slug: "cognism" },
  { name: "Cognition", ats: "ashby", slug: "cognition" },
  { name: "Cohere", ats: "ashby", slug: "cohere" },
  { name: "Coinbase", ats: "greenhouse", slug: "coinbase" },
  { name: "Contentful", ats: "greenhouse", slug: "contentful" },
  { name: "Contentsquare", ats: "lever", slug: "contentsquare" },
  { name: "Coupa", ats: "lever", slug: "coupa" },
  { name: "Culture Amp", ats: "greenhouse", slug: "cultureamp" },
  { name: "Cursor", ats: "ashby", slug: "cursor" },
  { name: "CuspAI", ats: "ashby", slug: "cuspai" },
  { name: "Cyberhaven", ats: "ashby", slug: "cyberhaven" },
  { name: "Databricks", ats: "greenhouse", slug: "databricks" },
  { name: "Datadog", ats: "greenhouse", slug: "datadog" },
  { name: "DeepL", ats: "ashby", slug: "deepl" },
  { name: "Deliveroo", ats: "greenhouse", slug: "deliveroo" },
  { name: "Dialpad", ats: "greenhouse", slug: "dialpad" },
  { name: "Docker", ats: "ashby", slug: "docker" },
  { name: "Dojo", ats: "greenhouse", slug: "dojo" },
  { name: "Dropbox", ats: "greenhouse", slug: "dropbox" },
  { name: "Duolingo", ats: "greenhouse", slug: "duolingo" },
  { name: "Elastic", ats: "greenhouse", slug: "elastic" },
  { name: "ElevenLabs", ats: "ashby", slug: "elevenlabs" },
  { name: "Elliptic", ats: "ashby", slug: "elliptic" },
  { name: "Epic Games", ats: "greenhouse", slug: "epicgames" },
  { name: "Faculty", ats: "ashby", slug: "faculty" },
  { name: "Farfetch", ats: "lever", slug: "farfetch" },
  { name: "Figma", ats: "greenhouse", slug: "figma" },
  { name: "Fivetran", ats: "greenhouse", slug: "fivetran" },
  { name: "Flock", ats: "ashby", slug: "flock" },
  { name: "Flow Traders", ats: "greenhouse", slug: "flowtraders" },
  { name: "Form3", ats: "greenhouse", slug: "form3" },
  { name: "FREENOW", ats: "greenhouse", slug: "freenow" },
  { name: "Freetrade", ats: "ashby", slug: "freetrade" },
  { name: "Funding Circle", ats: "ashby", slug: "fundingcircle" },
  { name: "GitLab", ats: "greenhouse", slug: "gitlab" },
  { name: "GoCardless", ats: "greenhouse", slug: "gocardless" },
  { name: "Grafana", ats: "greenhouse", slug: "grafanalabs" },
  { name: "Graphcore", ats: "greenhouse", slug: "graphcore" },
  { name: "Griffin", ats: "ashby", slug: "griffin" },
  { name: "Gymshark", ats: "greenhouse", slug: "gymshark" },
  { name: "H Company", ats: "ashby", slug: "hcompany" },
  { name: "Healx", ats: "lever", slug: "healx" },
  { name: "HelloFresh", ats: "greenhouse", slug: "hellofresh" },
  { name: "Helsing", ats: "greenhouse", slug: "helsing" },
  { name: "Hopper", ats: "ashby", slug: "hopper" },
  { name: "IMC Trading", ats: "greenhouse", slug: "imc" },
  { name: "Immersive Labs", ats: "ashby", slug: "immersivelabs" },
  { name: "Intercom", ats: "greenhouse", slug: "intercom" },
  { name: "IonQ", ats: "greenhouse", slug: "ionq" },
  { name: "Isomorphic Labs", ats: "greenhouse", slug: "isomorphiclabs" },
  { name: "Jane Street", ats: "greenhouse", slug: "janestreet" },
  { name: "JetBrains", ats: "greenhouse", slug: "jetbrains" },
  { name: "Jump Trading", ats: "greenhouse", slug: "jumptrading" },
  { name: "Kaluza", ats: "greenhouse", slug: "kaluza" },
  { name: "Kayak", ats: "ashby", slug: "kayak" },
  { name: "Klaviyo", ats: "greenhouse", slug: "klaviyo" },
  { name: "Lattice", ats: "greenhouse", slug: "lattice" },
  { name: "Lendable", ats: "ashby", slug: "lendable" },
  { name: "Lindus", ats: "ashby", slug: "lindus" },
  { name: "Linear", ats: "ashby", slug: "linear" },
  { name: "Lovable", ats: "ashby", slug: "lovable" },
  { name: "Man Group", ats: "greenhouse", slug: "mangroup" },
  { name: "Mapbox", ats: "ashby", slug: "mapbox" },
  { name: "Marshmallow", ats: "ashby", slug: "marshmallow" },
  { name: "Mixpanel", ats: "greenhouse", slug: "mixpanel" },
  { name: "Mollie", ats: "ashby", slug: "mollie" },
  { name: "Moneybox", ats: "ashby", slug: "moneybox" },
  { name: "MongoDB", ats: "greenhouse", slug: "mongodb" },
  { name: "Monzo", ats: "greenhouse", slug: "monzo" },
  { name: "Moonpig", ats: "lever", slug: "moonpig" },
  { name: "Multiverse", ats: "ashby", slug: "multiverse" },
  { name: "Mux", ats: "ashby", slug: "mux" },
  { name: "Neo4j", ats: "greenhouse", slug: "neo4j" },
  { name: "Nothing", ats: "greenhouse", slug: "nothing" },
  { name: "Notion", ats: "ashby", slug: "notion" },
  { name: "OakNorth", ats: "ashby", slug: "oaknorth" },
  { name: "Ocado Group", ats: "greenhouse", slug: "ocadogroup" },
  { name: "Okta", ats: "greenhouse", slug: "okta" },
  { name: "OKX", ats: "greenhouse", slug: "okx" },
  { name: "OpenAI", ats: "ashby", slug: "openai" },
  { name: "Oyster", ats: "ashby", slug: "oyster" },
  { name: "Paddle", ats: "ashby", slug: "paddle" },
  { name: "Palantir", ats: "lever", slug: "palantir" },
  { name: "Parloa", ats: "greenhouse", slug: "parloa" },
  { name: "Pay.UK", ats: "greenhouse", slug: "payuk" },
  { name: "Peloton", ats: "greenhouse", slug: "peloton" },
  { name: "Pendo", ats: "greenhouse", slug: "pendo" },
  { name: "Pennylane", ats: "ashby", slug: "pennylane" },
  { name: "PhysicsX", ats: "greenhouse", slug: "physicsx" },
  { name: "Pigment", ats: "lever", slug: "pigment" },
  { name: "Pinterest", ats: "greenhouse", slug: "pinterest" },
  { name: "Plaid", ats: "ashby", slug: "plaid" },
  { name: "Pleo", ats: "ashby", slug: "pleo" },
  { name: "Point72", ats: "greenhouse", slug: "point72" },
  { name: "PostHog", ats: "ashby", slug: "posthog" },
  { name: "PsiQuantum", ats: "greenhouse", slug: "psiquantum" },
  { name: "Quantexa", ats: "ashby", slug: "quantexa" },
  { name: "Ramp", ats: "ashby", slug: "ramp" },
  { name: "Recorded Future", ats: "greenhouse", slug: "recordedfuture" },
  { name: "Reddit", ats: "greenhouse", slug: "reddit" },
  { name: "Redis", ats: "ashby", slug: "redis" },
  { name: "Replit", ats: "ashby", slug: "replit" },
  { name: "Rigetti", ats: "lever", slug: "rigetti" },
  { name: "Ripple", ats: "greenhouse", slug: "ripple" },
  { name: "Riverlane", ats: "greenhouse", slug: "riverlane" },
  { name: "Robinhood", ats: "greenhouse", slug: "robinhood" },
  { name: "Roblox", ats: "greenhouse", slug: "roblox" },
  { name: "Rubrik", ats: "greenhouse", slug: "rubrik" },
  { name: "Sanity", ats: "ashby", slug: "sanity" },
  { name: "Scale AI", ats: "greenhouse", slug: "scaleai" },
  { name: "Schonfeld", ats: "greenhouse", slug: "schonfeld" },
  { name: "Shield AI", ats: "lever", slug: "shieldai" },
  { name: "Snowflake", ats: "ashby", slug: "snowflake" },
  { name: "Sophos", ats: "lever", slug: "sophos" },
  { name: "Spire", ats: "greenhouse", slug: "spire" },
  { name: "Spotify", ats: "lever", slug: "spotify" },
  { name: "Squarepoint", ats: "greenhouse", slug: "squarepointcapital" },
  { name: "Starburst", ats: "greenhouse", slug: "starburst" },
  { name: "Strava", ats: "ashby", slug: "strava" },
  { name: "Stripe", ats: "greenhouse", slug: "stripe" },
  { name: "Sumo Logic", ats: "greenhouse", slug: "sumologic" },
  { name: "SumUp", ats: "greenhouse", slug: "sumup" },
  { name: "Supabase", ats: "ashby", slug: "supabase" },
  { name: "Synthesia", ats: "ashby", slug: "synthesia" },
  { name: "Tanium", ats: "greenhouse", slug: "tanium" },
  { name: "Teya", ats: "ashby", slug: "teya" },
  { name: "Tide", ats: "greenhouse", slug: "tide" },
  { name: "Tines", ats: "greenhouse", slug: "tines" },
  { name: "Tractable", ats: "ashby", slug: "tractable" },
  { name: "Trading 212", ats: "ashby", slug: "trading212" },
  { name: "Trainline", ats: "ashby", slug: "trainline" },
  { name: "TripAdvisor", ats: "greenhouse", slug: "tripadvisor" },
  { name: "TrueLayer", ats: "greenhouse", slug: "truelayer" },
  { name: "Trustpilot", ats: "greenhouse", slug: "trustpilot" },
  { name: "Twilio", ats: "greenhouse", slug: "twilio" },
  { name: "Unmind", ats: "ashby", slug: "unmind" },
  { name: "Veracode", ats: "greenhouse", slug: "veracode" },
  { name: "Vercel", ats: "greenhouse", slug: "vercel" },
  { name: "Virtu", ats: "greenhouse", slug: "virtu" },
  { name: "Vitesse", ats: "ashby", slug: "vitesse" },
  { name: "Vonage", ats: "greenhouse", slug: "vonage" },
  { name: "Wayflyer", ats: "ashby", slug: "wayflyer" },
  { name: "Wayve", ats: "ashby", slug: "wayve" },
  { name: "Webflow", ats: "greenhouse", slug: "webflow" },
  { name: "Winton", ats: "greenhouse", slug: "winton" },
  { name: "Wolt", ats: "greenhouse", slug: "wolt" },
  { name: "Wordsmith", ats: "ashby", slug: "wordsmith" },
  { name: "Xero", ats: "ashby", slug: "xero" },
  { name: "Zego", ats: "ashby", slug: "zego" },
  { name: "Zilch", ats: "ashby", slug: "zilch" },
  { name: "Zoe", ats: "ashby", slug: "zoe" },
  { name: "Zopa", ats: "lever", slug: "zopa" },
];
